# Generated by Django 4.1.4 on 2023-03-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, default='lt487nPq', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='callrequest',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
