# Generated by Django 4.1.4 on 2023-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='code',
            field=models.CharField(blank=True, default='V5xNAU13', max_length=8, null=True, unique=True),
        ),
    ]
